package com.nxecoii.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.nxecoii.greendao.SprayDetails;
import com.nxecoii.greendao.ScheduleData;
import com.nxecoii.greendao.WaterData;
import com.nxecoii.greendao.DownloadDBEntity;

import com.nxecoii.greendao.SprayDetailsDao;
import com.nxecoii.greendao.ScheduleDataDao;
import com.nxecoii.greendao.WaterDataDao;
import com.nxecoii.greendao.DownloadDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sprayDetailsDaoConfig;
    private final DaoConfig scheduleDataDaoConfig;
    private final DaoConfig waterDataDaoConfig;
    private final DaoConfig downloadDaoConfig;

    private final SprayDetailsDao sprayDetailsDao;
    private final ScheduleDataDao scheduleDataDao;
    private final WaterDataDao waterDataDao;
    private final DownloadDao downloadDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sprayDetailsDaoConfig = daoConfigMap.get(SprayDetailsDao.class).clone();
        sprayDetailsDaoConfig.initIdentityScope(type);

        scheduleDataDaoConfig = daoConfigMap.get(ScheduleDataDao.class).clone();
        scheduleDataDaoConfig.initIdentityScope(type);

        waterDataDaoConfig = daoConfigMap.get(WaterDataDao.class).clone();
        waterDataDaoConfig.initIdentityScope(type);

        downloadDaoConfig = daoConfigMap.get(DownloadDao.class).clone();
        downloadDaoConfig.initIdentityScope(type);

        sprayDetailsDao = new SprayDetailsDao(sprayDetailsDaoConfig, this);
        scheduleDataDao = new ScheduleDataDao(scheduleDataDaoConfig, this);
        waterDataDao = new WaterDataDao(waterDataDaoConfig, this);
        downloadDao = new DownloadDao(downloadDaoConfig, this);

        registerDao(SprayDetails.class, sprayDetailsDao);
        registerDao(ScheduleData.class, scheduleDataDao);
        registerDao(WaterData.class, waterDataDao);
        registerDao(DownloadDBEntity.class, downloadDao);
    }
    
    public void clear() {
        sprayDetailsDaoConfig.getIdentityScope().clear();
        scheduleDataDaoConfig.getIdentityScope().clear();
        waterDataDaoConfig.getIdentityScope().clear();
        downloadDaoConfig.getIdentityScope().clear();
    }

    public SprayDetailsDao getSprayDetailsDao() {
        return sprayDetailsDao;
    }

    public ScheduleDataDao getScheduleDataDao() {
        return scheduleDataDao;
    }

    public WaterDataDao getWaterDataDao() {
        return waterDataDao;
    }

    public DownloadDao getDownloadDao() {
        return downloadDao;
    }

}
