package com.nxecoii.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SCHEDULE_DATA".
 */
public class ScheduleData {

    private Long id;
    private Integer zone;
    private Integer repeat;
    private Integer interval;
    private Integer timeId;
    private Integer groupId;
    private String lable;
    private String start_time;
    private Boolean isUpload;
    private Boolean enable;
    private java.util.Date add_time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ScheduleData() {
    }

    public ScheduleData(Long id) {
        this.id = id;
    }

    public ScheduleData(Long id, Integer zone, Integer repeat, Integer interval, Integer timeId, Integer groupId, String lable, String start_time, Boolean isUpload, Boolean enable, java.util.Date add_time) {
        this.id = id;
        this.zone = zone;
        this.repeat = repeat;
        this.interval = interval;
        this.timeId = timeId;
        this.groupId = groupId;
        this.lable = lable;
        this.start_time = start_time;
        this.isUpload = isUpload;
        this.enable = enable;
        this.add_time = add_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getZone() {
        return zone;
    }

    public void setZone(Integer zone) {
        this.zone = zone;
    }

    public Integer getRepeat() {
        return repeat;
    }

    public void setRepeat(Integer repeat) {
        this.repeat = repeat;
    }

    public Integer getInterval() {
        return interval;
    }

    public void setInterval(Integer interval) {
        this.interval = interval;
    }

    public Integer getTimeId() {
        return timeId;
    }

    public void setTimeId(Integer timeId) {
        this.timeId = timeId;
    }

    public Integer getGroupId() {
        return groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public String getLable() {
        return lable;
    }

    public void setLable(String lable) {
        this.lable = lable;
    }

    public String getStart_time() {
        return start_time;
    }

    public void setStart_time(String start_time) {
        this.start_time = start_time;
    }

    public Boolean getIsUpload() {
        return isUpload;
    }

    public void setIsUpload(Boolean isUpload) {
        this.isUpload = isUpload;
    }

    public Boolean getEnable() {
        return enable;
    }

    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    public java.util.Date getAdd_time() {
        return add_time;
    }

    public void setAdd_time(java.util.Date add_time) {
        this.add_time = add_time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
