package com.nxecoii.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SPRAY_DETAILS".
 */
public class SprayDetails {

    private Long id;
    private Integer zone;
    private Integer adjust;
    private Integer intervalOrigin;
    private Integer intervalActual;
    private Integer sprayType;
    private Integer stopType;
    private Long startTimeTheory;
    private Long startTimeActually;
    private Long endTimeActually;
    private Boolean isUpload;
    private Boolean isSpraying;
    private java.util.Date add_time;

    // KEEP FIELDS - put your custom fields here

    public static final int sprayTypeAuto = 0;
    public static final int sprayTypeManual = 1;
    public static final int sprayTypeSchedule = 2;
    public static final int sprayTypeUnknow = 3;

    public static final int stopTypeAuto = 0;
    public static final int stopTypeManual = 1;
    public static final int stopTypePause = 2;
    public static final int stopTypeUnknow = 3;

    public static final String ID = "_id";
    public static final String ZONE = "zone";
    public static final String ADJUST = "adjust";
    public static final String INTERVAL_ORIGIN = "intervalOrigin";
    public static final String INTERVAL_ACTUAL = "intervalActual";
    public static final String IS_UPLOAD = "isUpload";
    public static final String START_TIME_THEORY = "startTimeTheory";
    //	public static final String END_TIME_THEORY = "endTimeTheory";
    public static final String START_TIME_ACTUALLY = "startTimeActually";
    public static final String END_TIME_ACTUALLY = "endTimeActually";
    public static final String SPRAY_TYPE = "sprayType";
    public static final String STOP_TYPE = "stopType";
    // KEEP FIELDS END

    public SprayDetails() {
    }

    public SprayDetails(Long id) {
        this.id = id;
    }

    public SprayDetails(Long id, Integer zone, Integer adjust, Integer intervalOrigin, Integer intervalActual, Integer sprayType, Integer stopType, Long startTimeTheory, Long startTimeActually, Long endTimeActually, Boolean isUpload, Boolean isSpraying, java.util.Date add_time) {
        this.id = id;
        this.zone = zone;
        this.adjust = adjust;
        this.intervalOrigin = intervalOrigin;
        this.intervalActual = intervalActual;
        this.sprayType = sprayType;
        this.stopType = stopType;
        this.startTimeTheory = startTimeTheory;
        this.startTimeActually = startTimeActually;
        this.endTimeActually = endTimeActually;
        this.isUpload = isUpload;
        this.isSpraying = isSpraying;
        this.add_time = add_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getZone() {
        return zone;
    }

    public void setZone(Integer zone) {
        this.zone = zone;
    }

    public Integer getAdjust() {
        return adjust;
    }

    public void setAdjust(Integer adjust) {
        this.adjust = adjust;
    }

    public Integer getIntervalOrigin() {
        return intervalOrigin;
    }

    public void setIntervalOrigin(Integer intervalOrigin) {
        this.intervalOrigin = intervalOrigin;
    }

    public Integer getIntervalActual() {
        return intervalActual;
    }

    public void setIntervalActual(Integer intervalActual) {
        this.intervalActual = intervalActual;
    }

    public Integer getSprayType() {
        return sprayType;
    }

    public void setSprayType(Integer sprayType) {
        this.sprayType = sprayType;
    }

    public Integer getStopType() {
        return stopType;
    }

    public void setStopType(Integer stopType) {
        this.stopType = stopType;
    }

    public Long getStartTimeTheory() {
        return startTimeTheory;
    }

    public void setStartTimeTheory(Long startTimeTheory) {
        this.startTimeTheory = startTimeTheory;
    }

    public Long getStartTimeActually() {
        return startTimeActually;
    }

    public void setStartTimeActually(Long startTimeActually) {
        this.startTimeActually = startTimeActually;
    }

    public Long getEndTimeActually() {
        return endTimeActually;
    }

    public void setEndTimeActually(Long endTimeActually) {
        this.endTimeActually = endTimeActually;
    }

    public Boolean getIsUpload() {
        return isUpload;
    }

    public void setIsUpload(Boolean isUpload) {
        this.isUpload = isUpload;
    }

    public Boolean getIsSpraying() {
        return isSpraying;
    }

    public void setIsSpraying(Boolean isSpraying) {
        this.isSpraying = isSpraying;
    }

    public java.util.Date getAdd_time() {
        return add_time;
    }

    public void setAdd_time(java.util.Date add_time) {
        this.add_time = add_time;
    }

    // KEEP METHODS - put your custom methods here

    public int getRemainTime() {
        return (intervalOrigin - intervalActual);
    }

    public void intervlActualAdd(int i) {
        intervalActual += i;
    }
    // KEEP METHODS END

}
